### PR TITLE
Allow HttpCheck to make a request with Basic Authentication

### PR DESCRIPTION
**Pull request by jperichon**
This allows a ```HttpCheck``` to make a request to a URL that includes basic authentication credentials.

eg: https://username:password@host.com/ping

I also added ```webmock``` as I wanted to stub only the HTTP request, without the timeout block.

### CODE REVIEW

**Comment by pbyrne** [comment]
This change seems reasonable; could you document it and add tests around it?

**Comment by jperichon** [comment]
@pbyrne I did a couple updates, how does it look now?

**Comment by pbyrne** [comment]
Looks good to me. @anfleene mind giving a second set of eyes in case I'm missing something?

**Comment by anfleene** [comment]
@jperichon mind adding a test that verifies basic auth works? I think the code looks good. But it would be nice to know that functionality doesn't break in the future.

**Comment by anfleene** [comment]
Closing this. This was sovled by #89

**Pull request closed without merging**
