### PR TITLE
Add a bundle-audit check

### PR DESCRIPTION
**Pull request by darrenleeweber**
Add a bundle-audit check. It has a `verbose` option that is `false` by default, to hide details.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Unit tests are passing OK, but this needs integration tests to fully exercise the bundle audit functionality in the context of an app that includes the bunder-audit gem.  At first glance, can't see how to do this directly in this project.

**Comment by pbyrne** [comment]
First of all, I apologize for the delay in responding.

Second, I'm not sure I think this belongs in the core `okcomputer` gem code since it seems distinct from the goal of providing application health checks. This feels like it might belong to CI or some other part of the deployment workflow, rather than a runtime check. I'm also reluctant to take on maintaining this check if and when Bundle Audit makes changes to its API in the future.

That said, I can understand that some people would like this kind of check available to them if they disagree with me. So as compromise, I'd be happy to link out in the README to a standalone gem that provides this check. We do this (for similar reasons) for [`okcomputer-grape`](https://github.com/sportngin/okcomputer#not-using-rails). How does that sound?

**Comment by darrenleeweber** [comment]
Is there any simple boiler-plate available to create a stand-alone gem that integrates with OKcomputer?

**Comment by pbyrne** [comment]
> Is there any simple boiler-plate available to create a stand-alone gem that integrates with OKcomputer?

None that I'm aware of. The general shape would probably look a lot like this:

* Depend on `okcomputer` in your .gemspec.
    * And probably a good idea to lock it to `'~> 1.13'` or similar, to avoid causing problems if we make breaking changes with v2.
* Then the bulk of your code would involve this PR's changes, namely providing `OkComputer:: BundleAuditCheck` as a subclass of `OkComputer::Check` (and its dependencies).
    * Shouldn't require any particular boilerplate. No need to put those dependencies inside `OkComputer` either.
    * Build the tests as you see fit (no need to use Rspec like we have here unless you prefer it)
* Then all you need in your README is how to register this check

**Comment by darrenleeweber** [comment]
Closing this PR to move the work into a stand-alone gem.

**Pull request closed without merging**
