### PR TITLE
Work better out-of-the-box on Rails 4.2

### LINKED ISSUE #52: Missing requirement: responders
I started using okcomputer for my rails app (Rails 4.2.0).

As Rails 4.2. doesn't ship with the responders gem it needs to be added to the Gemfile separately:

   gem "responders", "~> 2.0"
   gem "okcomputer" 

I don't know if it's possible to make it a requirement only for newer rails versions.

But anyway I think it should be part of the documentation

### PR DESCRIPTION
**Pull request by pbyrne**
Closes #52

### CODE REVIEW

**Comment by pbyrne** [comment]
@anfleene Any thoughts on this before I merge?

**Comment by anfleene** [comment]
Why did we have that respond_to in there in the first place? Just worried it might break it for rails 3.2

**Comment by anfleene** [comment]
also we might as well add ruby 2.(1,2) to our test suite.

**Comment by pbyrne** [comment]
> Why did we have that respond_to in there in the first place? Just worried it might break it for rails 3.2

No idea why that got there. Seems to work fine in Rails 3.2, per the tests and a local app. We do the per-action `respond_to`, so I don't think the controller-level one was giving us anything useful.

> also we might as well add ruby 2.(1,2) to our test suite

I'll add 2.1, but I don't think Rails works with 2.2 just yet.

**Comment by anfleene** [comment]
Awesome sounds good :+1:

**Pull request merged**
