### PR TITLE
Changes to make Rails not required

### PR DESCRIPTION
**Pull request by darbyfrey**
This is the follow up to this discussion: https://github.com/sportngin/okcomputer/pull/83. This should be all the changes required to make this work with my new `okcomputer-grape` gem. I'm going to close the original PR in favor of this one. Let me know if you see any issues with this approach.

### CODE REVIEW

**Comment by pbyrne** [comment]
These changes look good to me. @anfleene, any feedback before I merge this?

**Comment by anfleene** [comment]
Looks good. I always forget mattr_accessor and cattr_accessor are in activesupport :/

**Comment by pbyrne** [comment]
Merged and shipped as v1.6.6. Good luck and godspeed getting `okcomputer-grape` set up. Once it's available, we're happy to link to it from our README.

**Comment by darbyfrey** [comment]
Great, thanks guys!

I've got my first pass up here: https://github.com/bellycard/okcomputer-grape

The README still needs some love, but I'll take care of that this weekend.

**Comment by pbyrne** [comment]
Awesome. I've linked to it in our README with 22989b0. Thanks for contributing, and feel free to submit PRs if there are other areas to make this integration easier.

**Comment by darbyfrey** [comment]
Thanks @pbyrne!

**Pull request merged**
