### PR TITLE
Add GenericCacheCheck

### PR DESCRIPTION
**Pull request by pbyrne**
This closes https://github.com/sportngin/okcomputer/issues/60.

This should work with any cache system compatible with Rails, with any topology, unlike CacheCheck, which is specific to Memcached running locally. Additionally, I tweaked CacheCheck slightly (in a backwards-compatible way), to allow specifying an alternate host to check.

I avoided changing CacheCheck (like renaming it to MemcacheCheck) meaningfully since, now that we're at v1.0, we shouldn't be making breaking changes.

### CODE REVIEW

**Comment by pbyrne** [comment]
Pinging @dwbutler to verify that this does what he was proposing in #60 and @anfleene for some code review.

**Comment by dwbutler** [comment]
Yup, this looks like it will work. Thanks!

**Comment by anfleene** [comment]
Changes look good :+1: We really need to add some documentation. I didn't even know that other cache check existed.

**Comment by pbyrne** [comment]
> We really need to add some documentation.

Pull requests welcome. :trollface:

**Pull request merged**
