### PR TITLE
Add built-in resque scheduler check

### PR DESCRIPTION
**Pull request by agacode**
This is built-in check for resque-scheduler, it checks for the key that resque-scheduler creates in redis. That key is a TTL created to expire in 3 min, so when resque-scheduler is hasn't been started or is down for more than 3 min the check fails. I added the class ResqueSchedulerCheck and the corresponding spec

### CODE REVIEW

**Comment by anfleene** [comment]
Hi! Thanks for the PR. One question does this work with all versions of Resque Scheduler? I'm not sure that matters but we might want to document if it's only specific versions.

**Comment by agacode** [comment]
good question, i dont know haha, i can try with multiple versions and see
what happens

thank you

**Comment by agacode** [comment]
Hi! I have tested with almost all the versions of resque-scheduler. I works OK for the following versions:
`4.3.0, 4.2.1, 4.2.0, 4.1.0, 4.0.0, 3.1.0, 3.0.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.0` for the versions below 2.4.0 does not work since Resque.keys does not exist and it is a different key. There is a method master_lock_key to get the key but it is private, I don't want to violate the encapsulation by doing `Resque::Scheduler.send(:master_lock_key)`, I also don't want to create dependencies of modules or classes that might change their name or path for later versions of resque-scheduler. Please let me know if this PR can be merged specifying the versions in the list above, or if needs more work.

Thank you

**Comment by anfleene** [comment]
awesome, thanks for uncovering that. Since we don't have a clear place in the readme to document that, can you add a comment on the end of your readme update with something like 
```ruby
# Works on 2.4.0 and above versions of Resque Scheduler
```

**Comment by agacode** [comment]
Hi! Comment added to the README.markdown.
Thank you

**Comment by anfleene** [comment]
[Okcomputer 1.16.0](https://rubygems.org/gems/okcomputer/versions/1.16.0) is out on rubygems 🎉

**Comment by Cryptophobia** [comment]
Great job @agacode ! Go Arnaldo! Go Rails! Go Cuba! 🇨🇺 

My pocket:

**Pull request merged**
