### PR TITLE
Fixed Mongoid check for Mongoid 5

### PR DESCRIPTION
**Pull request by onomated**

### CODE REVIEW

**Comment by anfleene** [comment]
This looks good. 

Can you rebase with master. The version of bundler Travis installs by default doesn't work with newer versions of rubygems so I switched it to install the latest one.

Thanks!

**Comment by onomated** [comment]
Rebased and all checks passing.
Sorry for getting to this so late.  Was on vacation.

**Comment by anfleene** [comment]
Prefect thanks!

**Comment by anfleene** [comment]
okcomputer 1.6.4 is out on rubygems

**Comment by onomated** [comment]
Awesome! :+1:

**Pull request merged**
