### PR TITLE
Check name in CheckCollection#Register

### LINKED ISSUE #132: Check name missing when in CheckCollection
When registering a Check to a CheckCollection using the register instance method, the Check's name does not get set as it does when using the Registry's register class method. This causes the output to look like:

> Standard Checks
>   : PASSED Application is running (0s)
>   : PASSED Schema version: 20161208191710 (0s)
>   : PASSED Ruby 2.3.4-p301 (0s)

and the JSON output to have only one messge:

> {"":{"message":"Ruby 2.3.4-p301","success":true,"time":5.672976840287447e-06}}

### PR DESCRIPTION
**Pull request by elliott-beach**
Cut-and-paste code to implement @anfleene's suggestion in #132.
Fixes #132.

### CODE REVIEW

**Comment by anfleene** [comment]
Thanks for the PR!

**Comment by elliott-beach** [comment]
Thanks. I am working on making tests pass.

**Comment by anfleene** [comment]
@elliott-beach It looks like it broke a bunch of tests, most of which are double unexpected message errors.

**Comment by elliott-beach** [comment]
I am a ruby novice so I'm reading through some tutorials to figure it out; as my understanding of the syntax improves I should be able to fix it.

**Comment by anfleene** [comment]
Submitting a PR with failing tests is totally fine 👍  here's a way to get the tests to pass:

```ruby
module OkComputer
  describe CheckCollection do
    let(:foocheck) { double(:check) }
    let(:barcheck) { double(:check) }
    let(:registry) { {foo: foocheck, bar: barcheck} }

# ADD THESE Lines
    before do
      allow(foocheck).to receive(:registrant_name=)
      allow(barcheck).to receive(:registrant_name=)
    end

```

This will make the test doubles silently accept the method you're now calling.

**Comment by anfleene** [comment]
Thanks for the Contribution! [1.17.1](https://rubygems.org/gems/okcomputer/versions/1.17.1) is out on rubygems 🎉

**Pull request merged**
