### PR TITLE
Add new options for DelayedJobBackedUpCheck

### PR DESCRIPTION
**Pull request by johnnyshields**
There is no change to the existing behavior, these are purely new opts which will be useful to heavy users like me.

* queue - Used to monitor a specific delayed job queue (default: nil)
* include_locked - If true, will include currently locked jobs in the query (default: false)
* include_errored - If true, will include currently errored jobs in the query (default: false)

### One more thing:

OkComputer rocks, thank you for such a great gem. I went to upgrade it today and was pleasantly surprised to find new goodies (Elasticsearch, MongoidReplicaSet) which I can immediately use in production. Keep up the awesome work!!

### CODE REVIEW

**Comment by pbyrne** [comment]
These changes look good to me. Could you squash your commits into one, then I think it's good to merge. @anfleene, any thoughts?

**Comment by anfleene** [comment]
Looks good to me :+1:

**Comment by johnnyshields** [comment]
squashed!

**Comment by pbyrne** [comment]
:clap:

**Comment by pbyrne** [comment]
This is now available in v1.5.0.

**Pull request merged**
