### PR TITLE
Mongoid replica set check

### PR DESCRIPTION
**Pull request by dwbutler**
Hi,

This check meets two needs that the existing `MongoidCheck` does not:

 * Support checking connectivity to every node in the replica set.
 * Specify the Mongoid session to check.

Note that this check will NOT work if you're not running a replica set, which is why I created a separate class. This could potentially be merged with the original `MongoidCheck`.

### CODE REVIEW

**Comment by pbyrne** [comment]
CI [is currently failing](https://travis-ci.org/sportngin/okcomputer/builds/47655246), but I think that's just a problem in the new test (module v class for `Mongoid`?) rather than a problem with the new check. Can you take a look and clean that up?

As for the check itself, it looks good to me, but I've not got much experience working with Mongoid. @anfleene, your thoughts?

**Comment by dwbutler** [comment]
I see what happened. The existing `MongoidCheck` spec defined a stubbed out `Mongoid` class, when it should actually be a module. Pushed a fix, we'll see if Travis is happy.

I'd be happy to add some more technical documentation in the code as comments to explain a little better what's going on. That would probably be helpful for whoever wants to use it.

**Comment by pbyrne** [comment]
> I see what happened. The existing MongoidCheck spec defined a stubbed out Mongoid class, when it should actually be a module.

:clap:

> I'd be happy to add some more technical documentation in the code as comments to explain a little better what's going on.

That'd be nice, actually. Maybe at the top of the file, a sentence or two outlining the purpose of the check. That'd be a good pattern for us to have the other checks, for that matter, so might as well start here.

**Comment by anfleene** [comment]
Does this fail if the replset is having issues? It doesn't seem to be parsing the output of `replSetGetStatus` at all. Seems like it's just checking to see that the replset is configured properly and running not so much if all the members have replication caught up.

**Comment by dwbutler** [comment]
Travis is happy now.

I added some technical documentation to the `MongoidReplicaSetCheck`.

> Does this fail if the replset is having issues? It doesn't seem to be parsing the output of replSetGetStatus at all. Seems like it's just checking to see that the replset is configured properly and running not so much if all the members have replication caught up.

I considered this, but I didn't want to turn this into a full-blown monitoring solution for  mongodb. My main purpose with this check was to test connectivity from the app server to the replica set nodes.

I agree that a minimal parsing of `replSetGetStatus` could yield some useful information. I'll think about it some more.

**Comment by anfleene** [comment]
ah ok. I'm sort of wondering how different it is from the other Mongoid check then. What didn't work with the our current Check?

**Comment by dwbutler** [comment]
The current check only communicates with one node during the check, rather than all of them. So if one secondary is down, the check may succeed for a while and randomly fail when the node is selected.

I also needed to select a session other than the default. We have multiple mongodb clusters configured in different Mongoid sessions.

It turns out that Moped automatically excludes nodes that are recovering/unavailable. I'm working on communicating with at least the primary and one secondary to ensure that the database is accepting writes / reads.

**Comment by anfleene** [comment]
Ok. That makes sense. Sorry for the confusion. We only use a single mongo cluster in production and don't use our secondaries for anything other than a hot standby for Mongo to failover to. I kind of feel like it might be worth making the current check better to meet your needs but at the same time not everyone cares if one of their cluster members has dropped off the face of the planet. If you aren't using it it's not that big of a deal. So making them two distinct checks makes sense.

Are you actively making a change? Or are you satisfied with it's current version?

**Comment by dwbutler** [comment]
Interesting... We distribute reads to the secondaries, so it's important to us that Mongoid is able to communicate with all of them.

I'm actively working on a change and will push it soon.

**Comment by pbyrne** [comment]
@dwbutler, could you squash these into a single commit? Once that's done, I think this is good to merge.

**Comment by dwbutler** [comment]
Squashed.

**Pull request merged**
