### PR TITLE
Add tests for Rails 7

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Review by anfleene — APPROVED** [review]

**Comment by Spone** [comment]
If the gem is compatible with Rails 7, it would be great to merge this and update the README :pray:

**Comment by priverop** [comment]
Hey, any news on this? @anfleene Can I help?

**Comment by anfleene** [comment]
I no longer have commit bit on this repo so I won't be much help unfortunately. @natejgreene any chance you can get this merged?

**Comment by hlascelles** [comment]
@natejgreene Could you get this in please? Thanks!

**Review by natejgreene — APPROVED** [review]

**Comment by natejgreene** [comment]
Thanks!

**Pull request merged**
